### ISSUE TITLE
メッセージが表示されない

### ISSUE THREAD

**Issue by mewmo** [linyows/github-issues-notice#7]
日本語で失礼します。ペパボのmewmoです。
社内で試験的に使ってみたところ、メッセージがうまく表示されない様子だったので報告します。

▼設定したスプレッドシートのキャプチャ
<img width="415" alt="スクリーンショット 2021-12-01 18 14 31" src="https://user-images.githubusercontent.com/55735631/144207133-3c20711a-6539-4e5f-989b-98955a08efc3.png">

▼実際にSlackで通知された状態のキャプチャ
![スクリーンショット 2021-12-01 18 14 09](https://user-images.githubusercontent.com/55735631/144207257-32ee96c3-e721-4659-8f8c-feb016c83d55.png)

なにか設定方法など間違ってる点があったらすみません。ご指摘いただけますと幸いです。

**Comment by linyows** [comment]
@mewmo 閾値を超えてないのでメッセージが出ていないようです。必ずメッセージを出したい場合は、Thresholdを0にしてください 🙏

**Comment by mewmo** [comment]
うおーそういうことでしたか！失礼しました！:pray:
